##
## Export all variables to sub-invocation
##
export

bootstrap:
	echo "Makefile.bootstrap"
	echo ${REL_TYPE}
	echo ${PKG_VARS_CONFIG}
	echo ${PKG_ID}
	mkdir -p $(PKG_ID)/debian
	cd $(PKG_ID)/debian && $(REBAR) -v create \
                              template_dir=../$(DEPS_DIR)/node_package/priv/templates \
                              template_vars=../$(PKG_VARS_CONFIG) template=deb
	make -C $(PKG_ID) -f debian/Makefile
