
##
## Export all variables to sub-invocation
##
export

bootstrap:
	$(REBAR) -v create \
			template_dir=$(PKG_ID)/$(DEPS_DIR)/node_package/priv/templates \
			template_vars=$(PKG_ID)/$(PKG_VARS_CONFIG) template=osx
	make -f Makefile
